language: php

dist: focal

addons:
  apt:
    packages:
      - "libonig5"

matrix:
    include:
        - php: 7.4
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
                PHPUNIT_CONFIG='phpunit.xml.dist'
        - php: 7.4
          env:
                PHPUNIT_CONFIG='phpunit.xml.dist'
        - php: 8.0
          env:
                PHPUNIT_CONFIG='phpunit.xml.dist'
        - php: 8.1
          env:
                PHPUNIT_CONFIG='phpunit10.xml.dist'
        - php: 8.2
          env:
                PHPUNIT_CONFIG='phpunit10.xml.dist'

env:
    global:
        - ELASTICSEARCH_URL=http://127.0.0.1:9200

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_install:
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.8-amd64.deb
    - sudo dpkg -i --force-confnew elasticsearch-7.17.8-amd64.deb
    - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
    - sudo service elasticsearch restart

before_script:
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - phpenv config-rm xdebug.ini
    - export PATH="$HOME/bin:$PATH"
    - ./install_composer.sh
    - composer validate
    - composer update $COMPOSER_FLAGS

script:
    - composer sniffer
    - composer stan
    - rm -rf /tests/Bundle/DataGridBundle/Fixtures/var/test
    - rm -rf /tests/Bundle/DataSourceBundle/Fixtures/var/test
    - composer unit -- -c $PHPUNIT_CONFIG
