language: php

dist: focal

matrix:
    include:
        - php: 7.4
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
        - php: 8.0

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_script:
    - phpenv config-rm xdebug.ini
    - export PATH="$HOME/bin:$PATH"
    - ./install_composer.sh
    - composer validate
    - composer update $COMPOSER_FLAGS

script:
    - composer sniffer
    - composer stan
    - composer unit
