---
version: '3'

services:
    web:
        image: fsiopenpl/docker-php-apache:alpine-8.1
        container_name: data-web
        ports:
            - 80:80
            - 443:443
        environment:
            PHP_IDE_CONFIG: 'serverName=localhost'
            HOST_UID: 1000
            HOST_GID: 1000
        volumes:
            - .:/var/www/application
            - ~/.composer:/var/www/.composer
